### ISSUE TITLE
Replace ``PyAudio`` with ``PvRecorder``

### ISSUE THREAD

**Issue by edavalosanaya** [ChimeraPy/Engine#217]
Need to experiment with PvRecorder library: https://github.com/Picovoice/pvrecorder

**Comment by edavalosanaya** [comment]
Or consider using SoundCard library instead: https://github.com/bastibe/SoundCard

**Comment by edavalosanaya** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Processing Embodied Learning Data](https://trello.com/c/QfZBeaYW/77-processing-embodied-learning-data)

**Comment by umesh-timalsina** [comment]
It seems like we are only using `pyaudio` to get the sample size from the datachunk. What might be worth looking into for each of the libraries is whether we need them as dependencies? 

https://github.com/ChimeraPy/Engine/blob/0ab869c229cc2d0aed4081da342e6f57710c6604/chimerapy/engine/records/audio_record.py#L35-L37

**Comment by umesh-timalsina** [comment]
I have been maintaining the following [gist](https://gist.github.com/umesh-timalsina/5c13b53ebb1159a29d776dccabd19728) as a comparison between the libraries mentioned here. From the looks of it, it looks like we don't need any sound library, but rather expose the [`Wave_write.set_params`](https://docs.python.org/3/library/wave.html#wave.Wave_write.setparams) to the [`save_audio`](https://github.com/ChimeraPy/Engine/blob/0ab869c229cc2d0aed4081da342e6f57710c6604/chimerapy/engine/node/node.py#L215-L217), function.

**Comment by umesh-timalsina** [comment]
By the looks of it, `SoundCard` seems to be untouched in 5 years. While it says on the face that it doesn't resort on CPython extensions, it seems to have some issues with Windows.

- Windows/WASAPI currently records garbage if you record only a single channel. The reason for this is yet unknown. Multi-channel and channel maps work, though.
- Windows/WASAPI silently ignores the blocksize in some cases. Apparently, it only supports variable block sizes in exclusive mode.
- Error messages often report some internal CFFI/backend errors. This will be improved in the future.

**Comment by edavalosanaya** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maintenance](https://trello.com/c/KcMytZvP/6-maintenance)
