### ISSUE TITLE
VideoRecord adding initial frozen frames

### ISSUE THREAD

**Issue by umesh-timalsina** [ChimeraPy/Engine#243]
It seems like the video writer is adding initial frozen frames, hence the synchronized collection of data is erroneous. Here's a [sample run log directory](https://vanderbilt.box.com/s/5k9jy1cdhmhnysdihk13xtxpcd4j2flc). We are trying to record both audio and video in sync. But the audio's length is almost 20 seconds less than the video length. And the first 20 seconds of the video are just frozen frames.

**Comment by umesh-timalsina** [comment]
The root of this issue seems to be that the video writer is using `elapsed` key sent from the data_chunk, which is being added in the **[`save_video`](https://github.com/ChimeraPy/Engine/blob/aa63f328da9945c0c08543e31a4e1cc5b082a46e/chimerapy/engine/node/node.py#L210)** function. Now that the operations are triggered based on async Events(hence slower). A node's start time might not be representative of the time when it actually started recording, which I think was the goal of the **[`start_time`](https://github.com/ChimeraPy/Engine/blob/aa63f328da9945c0c08543e31a4e1cc5b082a46e/chimerapy/engine/node/node.py#L92)** function anyway. There are a couple of ways to remedy this:
1. Each FSM's state changed should trigger its own timestamp.
2. Each recorder should bookkeep it's start time, and account for dropped or extra data.

Thoughts, @edavalosanaya?

**Comment by edavalosanaya** [comment]
Yes, that makes sense. Let's try that idea

**Comment by edavalosanaya** [comment]
I am leaning towards option 2. It makes more sense to me.
